import os
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# Database path (local SQLite file or dynamically loaded environment variable)
DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    # Default to user's live Supabase PostgreSQL database in the cloud
    DATABASE_URL = "postgresql://postgres:R6eWAsaTozqUrU3Z@db.vmcdfwclwdnfehajhcsd.supabase.co:5432/postgres"

# Modern SQLAlchemy (1.4+) deprecates the 'postgres://' prefix in favor of 'postgresql://'
# Automatically rewrite this to support legacy prefixes generated by standard cloud databases.
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

# Conditionally pass SQLite connect_args only if we are using an SQLite engine
engine_args = {}
if DATABASE_URL.startswith("sqlite"):
    engine_args["connect_args"] = {"check_same_thread": False}

engine = create_engine(DATABASE_URL, **engine_args)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
